version: "3.8"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    restart: always
    ports:
      - 3001:3001
    environment:
      - PORT=3001

  server:
    container_name: server
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - SERVER_PORT=4000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres?schema=public
      - OPENAI_API_KEY=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
      - OPENAI_LLM_MODEL=text-embedding-3-large

  postgres:
    image: ankane/pgvector
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  # ipfs:
  #   image: ipfs/kubo:master-2024-05-06-2841ec0
  #   ports:
  #     - 4001:4001
  #     - 4001:4001/udp
  #     - 8080:8080
  #     - 5001:5001
  #   volumes:
  #     - ./ipfs/export:/export
  #     - ./ipfs/data:/data/ipfs

volumes:
  postgres:
